import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-tenant-improvement-allowance-recovery",
  "engine": "recovery",
  "title": "Tenant Improvement Allowance Recovery",
  "shortTitle": "Tenant Improvement Allowance Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through tenant improvement allowance recovery",
  "industry": "Commercial Lease Incentive Recovery",
  "uiPort": 4614,
  "apiPort": 5614,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Tenant Improvement Allowance Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Landlord Reimbursement",
    "expectedLabel": "Eligible Allowance Draw",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Tenant Improvement Allowance Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("lease-amendment-library","TIA01","Lease amendment library","Execute lease amendment library using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed lease amendment library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Lease amendment library Reference","text","TIA01-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("allowance-definition-extraction","TIA02","Allowance definition extraction","Execute allowance definition extraction using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed allowance definition extraction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Allowance definition extraction Reference","text","TIA02-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("premises-project-registry","TIA03","Premises project registry","Execute premises project registry using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed premises project registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Premises project registry Reference","text","TIA03-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("budget-draw-schedule","TIA04","Budget draw schedule","Execute budget draw schedule using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed budget draw schedule decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Budget draw schedule Reference","text","TIA04-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("eligible-cost-classification","TIA05","Eligible cost classification","Execute eligible cost classification using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed eligible cost classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Eligible cost classification Reference","text","TIA05-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("contractor-invoice-evidence","TIA06","Contractor invoice evidence","Execute contractor invoice evidence using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed contractor invoice evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Contractor invoice evidence Reference","text","TIA06-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("lien-waiver-collection","TIA07","Lien waiver collection","Execute lien waiver collection using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed lien waiver collection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Lien waiver collection Reference","text","TIA07-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("completion-milestone-tracking","TIA08","Completion milestone tracking","Execute completion milestone tracking using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed completion milestone tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Completion milestone tracking Reference","text","TIA08-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("landlord-approval-conditions","TIA09","Landlord approval conditions","Execute landlord approval conditions using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed landlord approval conditions decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Landlord approval conditions Reference","text","TIA09-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("submission-deadline-control","TIA10","Submission deadline control","Execute submission deadline control using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed submission deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Submission deadline control Reference","text","TIA10-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("draw-package-generation","TIA11","Draw package generation","Execute draw package generation using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed draw package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Draw package generation Reference","text","TIA11-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("information-request-workflow","TIA12","Information request workflow","Execute information request workflow using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed information request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Information request workflow Reference","text","TIA12-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("reimbursement-tracking","TIA13","Reimbursement tracking","Execute reimbursement tracking using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed reimbursement tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Reimbursement tracking Reference","text","TIA13-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("unused-allowance-forecast","TIA14","Unused allowance forecast","Execute unused allowance forecast using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed unused allowance forecast decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Unused allowance forecast Reference","text","TIA14-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]}),
feature("portfolio-recovery-analytics","TIA15","Portfolio recovery analytics","Execute portfolio recovery analytics using leases, amendments, allowance definitions, premises, construction budgets, draw schedules, contractor invoices, lien waivers, milestones, approvals, submissions, and reimbursements.","Produce a governed portfolio recovery analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Landlord / Tenant Project","text","Landlord / Tenant Project · Standard Case"],["caseReference","Portfolio recovery analytics Reference","text","TIA15-2026-001"],["reimbursedAmount","Landlord Reimbursement","currency",845500],["eligibleAmount","Eligible Allowance Draw","currency",997690],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"reimbursedAmount",subjects:["Lease amendment library case","Allowance definition extraction case","Premises project registry case","Budget draw schedule case","Eligible cost classification case"]})
]);
